### ISSUE TITLE
Remove mkdirp with fs.mkdir recursive ?

### ISSUE THREAD

**Issue by fraxken** [npm/git#1]
# What / Why
Hi, would you be ok for a pull-request to replace mkdirp with the new native fs.mkdir recursive method ?

This is a Node.js 10.12.0 addition and Node.js 8 is EOL now so i guess the timing is ok.

Best Regards,
Thomas

**Comment by isaacs** [comment]
mkdirp v1 uses fs.mkdir when available, and also polyfills for windows errors and returning the first made directory in versions that don't support that by default.

So, what's there is ideal.  Especially since this module supports node versions from 10.0 through 10.11 as well.
