### ISSUE TITLE
[BUG] GIT_SSH_COMMAND should honor GIT_SSH

### ISSUE THREAD

**Issue by mvorisek** [npm/git#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently `GIT_SSH_COMMAND` has hardcoded `ssh` path in https://github.com/npm/git/blob/v4.0.4/lib/opts.js#L5

But there is also `GIT_SSH` env. var honored by standard git. The `GIT_SSH_COMMAND` should use `GIT_SSH` (and quoted) instead of `ssh` when `GIT_SSH` is non-empty.

Will fix https://github.com/npm/cli/issues/2891 as I can confirm https://github.com/npm/cli/issues/2891#issuecomment-959213034 fixes the problem.

![image](https://user-images.githubusercontent.com/2228672/232171169-a7c30cc8-4aa1-497b-8ee2-bb7b5c575b19.png)

### Expected Behavior

`GIT_SSH` other than `ssh`/empty is honored.

**Comment by dennishenry** [comment]
Opened a PR to offer to resolve this: https://github.com/npm/git/pull/194

**Comment by dennishenry** [comment]
This issue is now resolved in `npm` version `10.8.2` which has my PR above in it: https://github.com/npm/cli/releases/tag/v10.8.2

@wraithgar I think this can be closed now

**Comment by mvorisek** [comment]
Sure and thank you ❤
